version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: my-jenkins-container
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"

volumes:
  jenkins_home:
